package parking.pojo;

import org.springframework.stereotype.Repository;

@Repository
public class User {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.id
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	private Integer id;
	private String od;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.username
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	private String username;

	public String getOd() {
		return od;
	}

	public void setOd(String od) {
		this.od = od;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.password
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.email
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.phone
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.balance
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	private Double balance = 0.00;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user.credit
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	private Integer credit = 1;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.id
	 *
	 * @return the value of user.id
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.id
	 *
	 * @param id the value for user.id
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.username
	 *
	 * @return the value of user.username
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.username
	 *
	 * @param username the value for user.username
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.password
	 *
	 * @return the value of user.password
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.password
	 *
	 * @param password the value for user.password
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.email
	 *
	 * @return the value of user.email
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.email
	 *
	 * @param email the value for user.email
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.phone
	 *
	 * @return the value of user.phone
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.phone
	 *
	 * @param phone the value for user.phone
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.balance
	 *
	 * @return the value of user.balance
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public Double getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.balance
	 *
	 * @param balance the value for user.balance
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public void setBalance(Double balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.credit
	 *
	 * @return the value of user.credit
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public Integer getCredit() {
		return credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.credit
	 *
	 * @param credit the value for user.credit
	 *
	 * @mbggenerated Fri Oct 18 18:36:35 CST 2019
	 */
	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	/**
	 * 
	 */
	public User() {
		super();
	}

	/**
	 * @param username
	 * @param password
	 */
	public User(String username, String password) {
		super();
		this.username = username;
		this.password = password;
	}

}